export const COUNTRIES: Countries[] = [
    // { code: 'AL', name: 'Albania' },
    { code: 'AT', name: 'Austria' },
    // { code: 'BA', name: 'Bosnia and Herzegovina' },
    { code: 'BE', name: 'Belgium' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'BY', name: 'Belarus' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'DE', name: 'Germany' },
    { code: 'DK', name: 'Denmark' },
    { code: 'EE', name: 'Estonia' },
    { code: 'ES', name: 'Spain' },
    { code: 'FI', name: 'Finland' },
    { code: 'FR', name: 'France' },
    { code: 'GR', name: 'Greece' },
    { code: 'HR', name: 'Croatia' },
    { code: 'HU', name: 'Hungary' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IT', name: 'Italy' },
    { code: 'LT', name: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'LV', name: 'Latvia' },
    // { code: 'MD', name: 'Moldova' },
    // { code: 'ME', name: 'Montenegro' },
    // { code: 'MK', name: 'North Macedonia' },
    { code: 'MT', name: 'Malta' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'PL', name: 'Poland' },
    { code: 'PT', name: 'Portugal' },
    { code: 'RO', name: 'Romania' },
    // { code: 'RS', name: 'Serbia' },
    { code: 'RU', name: 'Russia' },
    { code: 'SE', name: 'Sweden' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'SK', name: 'Slovakia' },
    // { code: 'UA', name: 'Ukraine' },
];

export const ZIP_CODE_PATTERNS: Record<string, { pattern: RegExp; example: string }> = {
    DE: { pattern: /^\d{5}$/, example: '10115' },
    FR: { pattern: /^\d{5}$/, example: '75001' },
    AT: { pattern: /^\d{4}$/, example: '1010' },
    BE: { pattern: /^\d{4}$/, example: '1000' },
    BG: { pattern: /^\d{4}$/, example: '1000' },
    HR: { pattern: /^\d{5}$/, example: '10000' },
    CY: { pattern: /^\d{4}$/, example: '1010' },
    CZ: { pattern: /^\d{5}$/, example: '11000' },
    DK: { pattern: /^\d{4}$/, example: '2300' },
    EE: { pattern: /^\d{5}$/, example: '10111' },
    FI: { pattern: /^\d{5}$/, example: '00100' },
    GR: { pattern: /^\d{5}$/, example: '10434' },
    HU: { pattern: /^\d{4}$/, example: '1051' },
    IE: { pattern: /^[AC-FHKNPRTV-Y]{2}\d{2} ?[\dAC-FHKNPRTV-Y]{4}$/, example: 'D06X77' },
    IT: { pattern: /^\d{5}$/, example: '00186' },
    LV: { pattern: /^\d{4}$/, example: '1050' },
    LT: { pattern: /^\d{5}$/, example: '01100' },
    LU: { pattern: /^\d{4}$/, example: '1010' },
    MT: { pattern: /^\d{4}$/, example: 'VAL 1000' },
    NL: { pattern: /^\d{4} ?[A-Z]{2}$/, example: '1012AB' },
    PL: { pattern: /^\d{2}-\d{3}$/, example: '00-001' },
    PT: { pattern: /^\d{4}-\d{3}$/, example: '1000-100' },
    RO: { pattern: /^\d{6}$/, example: '010011' },
    SK: { pattern: /^\d{3} ?\d{2}$/, example: '811 01' },
    SI: { pattern: /^\d{4}$/, example: '1000' },
    ES: { pattern: /^\d{5}$/, example: '28001' },
    SE: { pattern: /^\d{3} ?\d{2}$/, example: '111 21' },
    // BA: { pattern: /^\d{5}$/, example: '71000' },
    // AL: { pattern: /^\d{4}$/, example: '1001' },
    // MD: { pattern: /^\d{4}$/, example: '2001' },
    // ME: { pattern: /^\d{5}$/, example: '81000' },
    // MK: { pattern: /^\d{4}$/, example: '1000' },
    // RS: { pattern: /^\d{6}$/, example: '11000' },
    // UA: { pattern: /^\d{5}$/, example: '01001' },
    BY: { pattern: /^\d{6}$/, example: '220000' },
    RU: { pattern: /^\d{6}$/, example: '101000' },
};

export type Countries = {
    code: string;
    name: string;
};
