import { genStyles } from '../../utils/generate-styles';

export const STYLES = genStyles({
    productContainer: {
        width: '100%',
        minWidth: '1180px',
        margin: '0 auto',
        '@media (max-width: 950px)': {
            minWidth: '500px',
        },
    },
    product: {
        width: '100%',
        borderRadius: '0',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '5.8rem',
        '@media (max-width: 950px)': {
            flexDirection: 'column',
            gap: '1.5rem',
        },
    },
    carousel: {
        height: '500px',
        width: '500px',
    },
    content: {
        maxWidth: '394px',
        width: '100%',
    },
    title: {
        mt: '0.625rem',
        mb: '1.25rem',
        fontFamily: 'Cormorant, serif',
        fontWeight: '400',
        fontSize: '3.25rem',
        lineHeight: '3.93rem',
        color: '#161412',
    },
    info: {
        mb: '0.5rem',
        width: '100%',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '0.45rem',
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '0.875rem',
        lineHeight: '1rem',
        color: '#65635F',
    },
    stone: {
        alignItems: 'flex-start',
        mb: '0.25rem',
    },
    material: {
        fontSize: '0.875rem',
        textTransform: 'capitalize',
    },
    gender: {
        fontSize: '0.875rem',
        textTransform: 'capitalize',
    },
    sku: {
        mb: '0.75rem',
    },
    text: {
        mb: '1.25rem',
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '1rem', //'0.875rem',
        lineHeight: '1.19rem',
        color: '#65635F',
        textAlign: 'left',
    },
    devider: {
        mb: '1.25rem',
    },
    priceContent: {
        mb: '1.25rem',
        width: '100%',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '1rem',
    },
    price: {
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '1.3rem',
        lineHeight: '1.5rem',
        color: '#161412',
    },
    oldPriceContent: {
        position: 'relative',
    },
    lineThrough: {
        position: 'absolute',
        left: 0,
        top: '50%',
        width: '100%',
        height: '2px',
        backgroundColor: 'rgba(197,9,9,0.7)',
        transform: 'translateY(-50%)',
    },
    oldPrice: {
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '1.3rem',
        lineHeight: '1.5rem',
        color: '#65635F',
    },
    productControls: {
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    skeletonBlock: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
});
