import { genStyles } from '../../utils/generate-styles';

export const STYLES = genStyles({
    personalNonEditableInfoContent: {
        mb: '0',
        display: 'flex',
        flexDirection: 'column',
        flexWrap: 'nowrap',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    personalEditableInfoContent: {
        mb: '0',
        display: 'flex',
        flexDirection: 'column',
        flexWrap: 'nowrap',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        position: 'relative',
    },
    personalNonEditableInfo: {
        mb: '1.7rem',
        display: 'flex',
        flexWrap: 'nowrap',
        flexDirection: 'row',
        gap: '1rem',
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: '100%',
    },
    personalEditableInfo: {
        mb: '1.7rem',
        display: 'flex',
        flexWrap: 'nowrap',
        flexDirection: 'row',
        gap: '1rem',
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: '100%',
    },
    personalItemTitle: {
        minWidth: '6.5rem',
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '1rem',
        lineHeight: '1.19rem',
        color: '#65635F',
        overflow: 'hidden',
    },
    personalItemInfo: {
        marginLeft: '0',
        maxWidth: '16rem',
        height: '2.5rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '1rem',
        lineHeight: '1.19rem',
        color: '#000000',
        letterSpacing: '0.1em',
        overflow: 'hidden',
    },
    editableField: {
        marginLeft: '0.875rem',
    },
    lastNameControl: {
        mb: '1.7rem',
    },
    birthControl: {
        mb: '1.7rem',
    },
    editControls: {
        mt: '0',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        gap: '0.7rem',
    },
    editButton: {
        maxWidth: '9.25rem',
        width: '100%',
        fontFamily: 'Jost, sans-serif',
        fontWeight: '400',
        fontSize: '0.75rem',
        lineHeight: '1.5rem',
        letterSpacing: '1px',
        pt: '0.375rem',
        pb: '0.375rem',
        boxShadow: 'unset',
        border: '1px solid #000',
        borderRadius: 0,
        transition: '0.3s all ease-in-out',
        '&:disabled': {
            border: '1px solid rgba(101, 99, 95, 0.65)',
            backgroundColor: 'rgba(101, 99, 95, 0.15)',
        },
    },
    saveButton: {
        mt: 0,
        mb: 0,
        color: '#FFF',
        backgroundColor: '#000',
        '&:hover': {
            color: '#000',
            border: '1px solid #000',
            backgroundColor: '#FFF',
        },
    },
    cancelButton: {
        mt: 0,
        color: '#65635F',
        backgroundColor: '#FFF',
        '&:hover': {
            color: '#000',
        },
    },
    errorForm: {
        width: '16rem',
        position: 'absolute',
        left: '7.5rem',
        top: '2.5rem',
        color: '#d20000',
        fontFamily: 'Arial',
        fontSize: '0.6rem',
    },
    dateInput: {
        mt: 0,
    },
});
