import { genStyles } from '../../utils/generate-styles';

export const STYLES = genStyles({
    paginationControls: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '0.4rem',
        mt: 4,
        mb: 0,
    },
    ellipsis: {
        // px: 1
    },
    paginationControlButton: {
        width: '45px',
        minWidth: '40px',
        cursor: 'pointer',
        padding: '0.15rem 0.5rem',
        border: '1px solid #65635f',
        borderRadius: '0.25rem',
        fontFamily: 'Jost, sans-serif',
        fontSize: '0.75rem',
        fontWeight: 300,
        lineHeight: '1rem',
        color: '#65635f',
        letterSpacing: 0,
        backgroundColor: '#fff',
        boxShadow: 'unset',
        transition: '0.3s all ease-in-out',
        '&:hover': {
            color: '#fff',
            backgroundColor: '#65635f',
        },
        '&:disabled': {
            pointerEvents: 'none',
            border: '1px solid rgba(101, 99, 95, 0.65)',
            opacity: 0.55,
            backgroundColor: 'rgba(101, 99, 95, 0.2)',
        },
    },
    paginationPageButton: {
        width: '35px',
        minWidth: '30px',
        mx: 0.25,
        cursor: 'pointer',
        padding: '0.25rem 0.5rem',
        border: '1px solid #65635f',
        borderRadius: '0.25rem',
        fontFamily: 'Jost, sans-serif',
        fontSize: '0.75rem',
        fontWeight: 300,
        lineHeight: '1rem',
        color: '#65635f',
        letterSpacing: 0,
        backgroundColor: '#fff',
        boxShadow: 'unset',
        transition: '0.3s all ease-in-out',
        '&:hover': {
            border: '1px solid rgba(101, 99, 95, 0.65)',
            backgroundColor: 'rgba(101, 99, 95, 0.15)',
        },
    },
    paginationActiveButton: {
        width: '40px',
        minWidth: '35px',
        mx: 0.5,
        pointerEvents: 'none',
        padding: '0.35rem 0.5rem',
        border: '1px solid #000',
        borderRadius: '0.25rem',
        fontFamily: 'Jost, sans-serif',
        fontSize: '0.75rem',
        fontWeight: 300,
        lineHeight: '1rem',
        color: '#FFF',
        letterSpacing: 0,
        backgroundColor: '#000',
        boxShadow: 'unset',
        transition: '0.3s all ease-in-out',
        '&:hover': {
            border: '1px solid rgba(101, 99, 95, 0.65)',
            backgroundColor: 'rgba(101, 99, 95, 0.15)',
        },
    },
});
